### PR TITLE
Update BatchStitchPooledCellPainting_StitchAndCrop_Headless.py

### PR DESCRIPTION
**Pull request by rsenft1**
This commit adds support for 293 and 88 site well acquisitions and also adds in a new option to NOT quarter round wells (important in the VarChAMP data since we don't have a nice # of sites that splits into 4 evenly and the # of images is small enough).

### CODE REVIEW

**Comment by bethac07** [comment]
This is awesome! Can you add this variable to the [batch jobs](https://github.com/broadinstitute/pooled-cell-painting-image-processing/blob/master/lambda/lambda_functions/create_batch_jobs.py) and the lamdas for steps 4 and 8 as part of this PR?

**Comment by rsenft1** [comment]
I believe I have added it where necessary: batch jobs functions for steps 4, 8, and 8Z and I added the variable to the lambda functions for steps 4 and 8 as well so `quarter_if_round` is passed in.

**Comment by ErinWeisbart** [comment]
Thanks @rsenft1. It also needs to be in the metadatatemplate. Do you mind adding it there too?

**Comment by ErinWeisbart** [comment]
Noting that at this point the script "works" and will stitch fully round wells without quartering.
However, there is still a single-tile-has-all-the-noise artifact https://github.com/broadinstitute/RebeccaSenft_Projects/issues/54

**Comment by ErinWeisbart** [comment]
Merging in, making new issue to track the stacking noise problem.

**Pull request merged**
